package player;

import java.util.Random;

import map.MapViewer;

public class AIPlayer implements Player {
	
	private String personalSymbol;
	private Move move;

	public boolean makeMove(MapViewer map) {
		//From what I can tell, the moves generated by easy mode are random.
		//Generate random number between 0 and 8, and that will be the move.
		Random randomGenerator = new Random();
		
		move = new Move();
		move.setPlayer(personalSymbol);
		move.setPosition(Integer.toString(randomGenerator.nextInt(9)));
		
		return map.updateMap(move);
	}

	public String getPersonalSymbol() {
		return personalSymbol;
	}

	public void setPersonalSymbol(String personalSymbol) {
		this.personalSymbol = personalSymbol;
	}

}
