package player;

import java.util.Random;

import map.Map;

public class AIPlayer implements Player {
	
	private String personalSymbol;
	private Move move;

	public boolean makeMove(Map map) {
		//From what I can tell, the moves generated by easy mode are random.
		//Generate random number between 0 and 8, and that will be the move.
		Random randomGenerator = new Random();
		
		move = new Move();
		move.setPlayer(personalSymbol);
		move.setPosition(Integer.toString(randomGenerator.nextInt(9)));
		
		return map.updateMap(Integer.parseInt(move.getPosition()), move.getPlayer());
	}

	public String getPersonalSymbol() {
		return personalSymbol;
	}

	public void setPersonalSymbol(String personalSymbol) {
		this.personalSymbol = personalSymbol;
	}

}
