package player;

import java.util.Random;

import map.BoardViewer;
import player.impl.PlayerDisplayInterface;

public class AIPlayer extends Player {

    public AIPlayer(PlayerDisplayInterface displayBridge) {
        super(displayBridge);
    }

	public boolean makeMove(BoardViewer board) {
		//From what I can tell, the moves generated by easy mode are random.
		//Generate random number between 0 and 8, and that will be the move.
		Random randomGenerator = new Random();
        int moveAttempt = randomGenerator.nextInt(9);
		
		move = new Move();
		move.setPlayer(personalSymbol);
		move.setPosition(Integer.toString(moveAttempt));
		
		return board.updateBoard(move);
	}

}
